security:
    encoders:
        Guestbook\AdminBundle\Entity\User:
            algorithm:        sha1
            encode_as_base64: false
            iterations:       1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: GuestbookAdminBundle:User, property: username }
            
    firewalls:
        general_area:
            pattern: /.*
            anonymous: ~
            form_login:
                login_path:  /admin/login
                check_path:  /admin/login_check
                
                # csrf token options
                csrf_parameter:  _csrf_token
                intention: authenticate
                
                default_target_path: /admin
            logout:
                path: /admin/logout
                target: /

                
    access_control:
        - { path: ^/admin/login.*, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin.*, roles: ROLE_USER }

        
