parameters:
#    guestbook_book.example.class: Guestbook\BookBundle\Example

services:
#    guestbook_book.example:
#        class: %guestbook_book.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
