parameters:
#    guestbook_admin.example.class: Guestbook\AdminBundle\Example

services:
#    guestbook_admin.example:
#        class: %guestbook_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
