<?php

namespace Guestbook\BookBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository {
    public function findAllPosts($approved = true) {
        return $this->createQueryBuilder('p')
            ->select('p')
            ->where('p.approved = :approved')
            ->setParameter('approved', (bool)$approved)
            ->addOrderBy('p.created', 'DESC')
            ->getQuery()
            ->getResult();
    }

}